#!/usr/lib/env python
#-*- coding=utf-8 -*-


import sys


reload(sys)
sys.setdefaultencoding('utf-8')


entity_list = {
    "欧元区CPI年率":{"names":["CPI同比","CPI年率","消费者物价指数年率","居民消费价格指数年率"],"nation":"EUR","frequency":"monthly","affectGold":"利空"},
    "欧元区CPI月率":{"names":["CPI月率","CPI环比","CPI月环比","消费者物价指数月率","居民消费价格指数月率"],"nation":"EUR","frequency":"monthly","affectGold":"利空"},
    "欧元区季调后GDP季率修正值":{"names":["季调后GDP季率修正值","GDP经季调季环比","名义国内生产总值季率修正值"],"nation":"EUR","frequency":"monthly","affectGold":"利空"},
    "欧元区季调后GDP季率初值":{"names":["季调后GDP季率初值","GDP经季调同比","名义国内生产总值季率初值"],"nation":"EUR","frequency":"quarterly","affectGold":"利空"},
    "欧元区制造业PMI":{"names":["制造业采购经理人指数","制造业PMI","PMI Manufacturing"],"nation":"EUR","frequency":"monthly","affectGold":"利空"},
    "欧洲央行基准利率":{"names":["央行基准利率","存款基准利率","央行利率决议"],"nation":"EUR","frequency":"monthly","affectGold":"利空"},
    "欧洲央行主要再融资利率":{"names":["主要再融资利率","再融资利率"],"nation":"EUR","frequency":"monthly","affectGold":"利空"},
    "欧元区消费者信心指数终值":{"names":["消费者信心指数终值","CCI终值"],"nation":"EUR","frequency":"monthly","affectGold":"利空"},
    "德国CPI年率":{"names":["CPI同比","CPI年率","消费者物价指数年率","居民消费价格指数年率"],"nation":"GER","frequency":"monthly","affectGold":"利空"},
    "德国CPI月率":{"names":["CPI月率","CPI环比","CPI月环比","消费者物价指数月率","居民消费价格指数月率"],"nation":"GER","frequency":"monthly","affectGold":"利空"},
    "德国季调后GDP季率初值":{"names":["GDP季率初值（季调后）","季调后GDP季率初值","GDP经季调同比","名义国内生产总值季率初值"],"nation":"GER","frequency":"quarterly","affectGold":"利空"},
    "IFO商业景气指数":{"names":["IFO企业景气指数","IFO商业景气指数","IFO经济景气指数"],"nation":"GER","frequency":"monthly","affectGold":"利空"},
    "德国制造业PMI初值":{"names":["制造业采购经理人指数初值","制造业PMI初值"],"nation":"GER","frequency":"monthly","affectGold":"利空"},
    "ZEW经济现况指数":{"names":["ZEW调查当前形势","ZEW经济现况指数"],"nation":"GER","frequency":"monthly","affectGold":"利空"},
    "ZEW经济景气指数":{"names":["ZEW经济景气指数","ZEW调查预期"],"nation":"GER","frequency":"monthly","affectGold":"利空"},
    "德国季调后制造业订单月率":{"names":["工厂订单月环比","制造业订单月率","工业订单(月率)"],"nation":"GER","frequency":"monthly","affectGold":"利空"},
    "德国失业人数变动":{"names":["失业人员变动","失业人数变动","失业人数","失业人数变化"],"nation":"GER","frequency":"monthly","affectGold":"利多"},
    "日本GDP平减指数年率初值":{"names":["GDP年平减指数初值","GDP平减指数年率初值"],"nation":"JPN","frequency":"quarterly","affectGold":"利空"},
    "日本实际GDP季率初值":{"names":["GDP经季调季环比","实际GDP季率初值","实际GDP(季率)"],"nation":"JPN","frequency":"quarterly","affectGold":"利空"},
    "日本实际GDP年化季率初值":{"names":["GDP年度化经季调季环比","实际GDP年化季率初值"],"nation":"JPN","frequency":"quarterly","affectGold":"利空"},
    "日本PPI年率":{"names":["PPI同比","PPI年率","生产价格指数年率",""],"nation":"JPN","frequency":"monthly","affectGold":"利空"},
    "日本东京CPI年率(除食品)":{"names":["东京消费价指(除生鲜食品)同比","日本东京CPI年率(除食品)","东京消费者物价指数年率"],"affectGold":""},
    "日本工业产出月率":{"names":["工业产出月率","工业产值(月环比)","工业产出(月率)"],"affectGold":""},
    "日本全国CPI年率":{"names":["全国CPI年率","日本国民消费物价指数同比(CPI)","全国核心消费者物价指数年率","全国消费者物价指数(CPI)"],"affectGold":""},
    "日本制造业PMI":{"names":["制造业PMI","日经日本制造业PMI","制造业采购经理人指数"],"affectGold":""},
    "日本失业率":{"names":["失业率"],"affectGold":""},
    "英国CPI年率":{"names":["CPI年率","CPI同比","消费者物价指数年率","居民消费价格指数月率"],"affectGold":""},
    "英国CPI月率":{"names":["CPI月率","CPI环比","CPI月环比","消费者物价指数月率","居民消费价格指数月率"],"affectGold":""},
    "英国GDP季率修正值":{"names":["季调后GDP季率","GDP经季调季环比","名义国内生产总值季率","GDP季率修正值"],"affectGold":""},
    "英国GDP经季调同比":{"names":["季调后GDP季率初值","GDP经季调同比","名义国内生产总值季率初值"],"affectGold":""},
    "英国制造业PMI":{"names":["制造业采购经理人指数","制造业PMI","PMI Manufacturing"],"affectGold":""},
    "英国未季调输出PPI年率":{"names":["PPI产出（未经季调）同比","未季调输出PPI年率","未季调生产者输出物价指数年率"],"affectGold":""},
    "英国未季调输出PPI月率":{"names":["PPI产出（未经季调）月环比","未季调输出PPI月率","未季调生产者输出物价指数月率"],"affectGold":""},
    "英国工业产出月率":{"names":["工业产出月率","英国工业产值(月环比)","工业产出(月率)"],"affectGold":""},
    "英国三个月ILO失业率":{"names":["三个月ILO失业率","国际劳工组织（ILO）失业率（3个月）"],"affectGold":""},
    "英国核心CPI年率":{"names":["核心CPI同比","核心CPI年率","核心消费者物价指数年率","核心居民消费价格指数年率"],"affectGold":""},
    "英国Nationwide房价指数年率":{"names":["Nationwide房价指数年率","全国房价指数未经季调同比","Nationwide房价指数(年率)"],"affectGold":""},
    "英国Nationwide房价指数月率":{"names":["Nationwide房价指数月率","全国房价指数月环比","Nationwide房价指数(月率)"],"affectGold":""},
    "英国失业金申请人数":{"names":["失业金申请人数","失业救济金申领人数变动","失业金申请人数变化"],"affectGold":""},
    "英国央行基准利率":{"names":["央行基准利率","央行银行利率","央行利率决议"],"affectGold":""},
    "英国季调后零售销售月率":{"names":["月环比零售营收除汽车燃料","季调后零售销售月率","季调后零售销售(月率)"],"affectGold":""},
    "英国制造业产出月率":{"names":["制造业生产月环比","制造业产出月率","工业产出月率","制造业生产月率"],"affectGold":""},
    "美国ADP就业人数变动":{"names":["ADP就业变动指数","ADP就业人数变动","ADP就业人数预估","ADP就业人数变化"],"affectGold":""},
    "美国CPI月率":{"names":["CPI月率","CPI环比","CPI月环比","消费者物价指数月率","居民消费价格指数月率"],"affectGold":""},
    "美国联邦公开市场委员会利率决定(利率上限)":{"names":["FOMC利率决策(上限)","联邦公开市场委员会利率决定(利率上限)","联邦基金利率目标","美联储利率决议"],"affectGold":""},
    "美国实际GDP年化季率终值":{"names":["GDP年度化季环比","实际GDP年化季率","实际国内生产总值年化季率"],"affectGold":""},
    "美国ISM制造业PMI":{"names":["ISM制造业PMI","ISM制造业指数","ISM制造业采购经理人指数"],"affectGold":""},
    "美国Markit制造业PMI":{"names":["Markit美国制造业采购经理指数","Markit制造业PMI","Markit制造业采购经理人指数"],"affectGold":""},
    "美国PPI月率":{"names":["美国PPI月率","美国PPI最终需求月环比","生产价格指数月率"],"affectGold":""},
    "季调后非农就业人口":{"names":["非农就业人数增减","季调后非农就业人口","非农就业人数变化","季调后非农就业人口变动"],"affectGold":""},
    "美国费城联储制造业指数":{"names":["费城联储制造业指数"],"affectGold":""},
    "美国个人支出":{"names":["个人支出","个人消费支出"],"affectGold":""},
    "美国个人收入":{"names":["个人收入"],"affectGold":""},
    "美国工厂订单":{"names":["工厂订单月率","工厂订单"],"affectGold":""},
    "美国工业产出月率":{"names":["工业产出月率","工业产出","工业生产月率","工业产出(月率)"],"affectGold":""},
    "美国营建支出月率":{"names":["建筑开支月环比","营建支出月率","营建支出(月率)"],"affectGold":""},
    "美国谘商会消费者信心指数":{"names":["谘商会消费者信心指数","经济咨商局消费者信心"],"affectGold":""},
    "美国零售销售月率":{"names":["零售销售月环比","零售销售月率","零售销售(月率)"],"affectGold":""},
    "美国贸易余额":{"names":["贸易帐","贸易余额"],"affectGold":""},
    "密歇根大学消费者信心指数":{"names":["密歇根大学信心","密歇根大学消费者信心指数"],"affectGold":""},
    "美国耐用品订单月率":{"names":["耐用品订单月率","耐用品订单","耐用品订单(月率)"],"affectGold":""},
    "美国批发库存月率":{"names":["批发库存月率","批发库存月环比","批发库存(月率)"],"affectGold":""},
    "美国失业率":{"names":["失业率"],"affectGold":""},
    "美国当周初请失业金人数":{"names":["当周初请失业金人数","初请失业金人数","上周季调后初请失业金人数"],"affectGold":""},
    "美国成屋销售总数年化":{"names":["成屋销售总数年化","现房销售","成屋销售","NAR季调后成屋销售总数年化"],"affectGold":""},
    "美国新屋销售总数年化":{"names":["新建住宅销售","新屋销售总数年化","新屋销售","新屋销售总数年化"],"affectGold":""},
    "美国新宅开工指数":{"names":["新屋开工总数年化","新宅开工指数","新屋开工"],"affectGold":""},
    "芝加哥采购经理指数":{"names":["芝加哥PMI","芝加哥采购经理指数","芝加哥采购经理人指数"],"affectGold":""},
}