#!/usr/lib/env python
#-*- coding=utf-8 -*-


import sys


reload(sys)
sys.setdefaultencoding('utf-8')


entity_list = {
    "欧元区CPI年率":{"names":["CPI同比","CPI年率","消费者物价指数年率","居民消费价格指数年率"],"nation":"EUR","frequency":"monthly","affectGold":"利空"},
    "欧元区CPI月率":{"names":["CPI月率","CPI环比","CPI月环比","消费者物价指数月率","居民消费价格指数月率"],"nation":"EUR","frequency":"monthly","affectGold":"利空"},
    "欧元区季调后GDP季率修正值":{"names":["季调后GDP季率修正值","GDP经季调季环比","名义国内生产总值季率修正值"],"nation":"EUR","frequency":"monthly","affectGold":"利空"},
    "欧元区季调后GDP季率初值":{"names":["季调后GDP季率初值","GDP经季调同比","名义国内生产总值季率初值"],"nation":"EUR","frequency":"quarterly","affectGold":"利空"},
    "欧元区制造业PMI初值":{"names":["制造业采购经理人指数初值","制造业PMI初值"],"nation":"EUR","frequency":"monthly","affectGold":"利空"},
    "欧洲央行基准利率":{"names":["央行基准利率","存款基准利率","央行利率决议"],"nation":"EUR","frequency":"monthly","affectGold":"利空"},
    "欧洲央行主要再融资利率":{"names":["主要再融资利率","再融资利率"],"nation":"EUR","frequency":"monthly","affectGold":"利空"},
    "欧元区消费者信心指数终值":{"names":["消费者信心指数终值","CCI终值"],"nation":"EUR","frequency":"monthly","affectGold":"利空"},
    "德国CPI年率":{"names":["CPI同比","CPI年率","消费者物价指数年率","居民消费价格指数年率"],"nation":"GER","frequency":"monthly","affectGold":"利空"},
    "德国CPI月率":{"names":["CPI月率","CPI环比","CPI月环比","消费者物价指数月率","居民消费价格指数月率"],"nation":"GER","frequency":"monthly","affectGold":"利空"},
    "德国季调后GDP季率初值":{"names":["GDP季率初值（季调后）","季调后GDP季率初值","GDP经季调同比","名义国内生产总值季率初值"],"nation":"GER","frequency":"quarterly","affectGold":"利空"},
    "IFO商业景气指数":{"names":["IFO企业景气指数","IFO商业景气指数","IFO经济景气指数"],"nation":"GER","frequency":"monthly","affectGold":"利空"},
    "德国制造业PMI初值":{"names":["制造业采购经理人指数初值","制造业PMI初值"],"nation":"GER","frequency":"monthly","affectGold":"利空"},
    "ZEW经济现况指数":{"names":["ZEW调查当前形势","ZEW经济现况指数"],"nation":"GER","frequency":"monthly","affectGold":"利空"},
    "ZEW经济景气指数":{"names":["ZEW经济景气指数","ZEW调查预期"],"nation":"GER","frequency":"monthly","affectGold":"利空"},
    "德国季调后制造业订单月率":{"names":["工厂订单月环比","制造业订单月率","工业订单(月率)"],"nation":"GER","frequency":"monthly","affectGold":"利空"},
    "德国失业人数变动":{"names":["失业人员变动","失业人数变动","失业人数","失业人数变化"],"nation":"GER","frequency":"monthly","affectGold":"利多"},
    "日本GDP平减指数年率初值":{"names":["GDP年平减指数初值","GDP平减指数年率初值"],"nation":"JPN","frequency":"quarterly","affectGold":"利空"},
    "日本实际GDP季率初值":{"names":["GDP经季调季环比","实际GDP季率初值","实际GDP(季率)"],"nation":"JPN","frequency":"quarterly","affectGold":"利空"},
    "日本实际GDP年化季率初值":{"names":["GDP年度化经季调季环比","实际GDP年化季率初值"],"nation":"JPN","frequency":"quarterly","affectGold":"利空"},
    "日本PPI年率":{"names":["PPI同比","PPI年率","生产价格指数年率",""],"nation":"JPN","frequency":"monthly","affectGold":"利空"},
    "东京消费价指(除生鲜食品)同比":'',
    "日本工业产值(月环比)":'',
    "日本国际收支经常项目余额":'',
    "日本国民消费物价指数同比(CPI)":'',
    "日经日本制造业PMI":'',
    "日本失业率":'',
    "英国CPI同比":'',
    "英国CPI月环比":'',
    "英国GDP经季调季环比":'',
    "英国GDP经季调同比":'',
    "Markit英国PMI Manufacturing SA":'',
    "PPI产出（未经季调）同比":'',
    "PPI产出（未经季调）月环比":'',
    "英国工业产值(月环比)":'',
    "英国国际劳工组织（ILO）失业率（3个月）":'',
    "英国核心CPI同比":'',
    "英国全国房价指数未经季调同比":'',
    "英国全国房价指数月环比":'',
    "英国失业救济金申领人数比率":'',
    "英国失业救济金申领人数变动":'',
    "英国央行银行利率":'',
    "英国月环比零售营收除汽车燃料":'',
    "英国制造业生产月环比":'',
    "美国ADP就业变动指数":'',
    "美国CPI月环比":'',
    "FOMC利率决策(上限)":'',
    "美国GDP年度化季环比":'',
    "美国ISM制造业":'',
    "Markit美国制造业采购经理指数":'',
    "美国PPI最终需求月环比":'',
    "美国非农就业人数增减":'',
    "美国费城联储企业前景":'',
    "美国个人开支":'',
    "美国个人收入":'',
    "美国工厂订单":'',
    "美国工业产值(月环比)":'',
    "美国建筑开支月环比":'',
    "美国经济咨商局消费者信心":'',
    "美国零售销售月环比":'',
    "美国贸易余额":'',
    "密歇根大学信心":'',
    "美国耐用品订单":'',
    "美国批发库存月环比":'',
    "美国失业率":'',
    "美国首次失业人数":'',
    "美国现房销售":'',
    "美国新建住宅销售":'',
    "美国新宅开工指数":'',
    "芝加哥采购经理指数":''
}